"""Tests for the highlight log output generated by the analyzer."""

from __future__ import annotations

from pathlib import Path
import sys

import numpy as np
import pytest
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from barchart.analyzer import BarchartOptionsAnalyzer, ProcessingResult


def _build_processing_result(tmp_path: Path, summary_df: pd.DataFrame | None = None) -> ProcessingResult:
    if summary_df is None:
        index = pd.Index([100.1234, 90.9876])
        summary_df = pd.DataFrame(
            {
                "Net_GEX": [150.6789, -200.4321],
                "Net_Vanna": [50.0, -60.0],
                "Call_Vanna": [80.3456, 40.7891],
                "Put_Vanna": [-30.4321, -90.9876],
                "Call_GEX": [90.0, 60.0],
                "Put_GEX": [60.0, -260.0],
                "Call_DEX": [600.0, 500.0],
                "Put_DEX": [400.0, 450.0],
                "Net_DEX": [1000.5678, 950.1234],
                "Call_TEX": [-120.6789, -80.9876],
                "Put_TEX": [-60.5432, -180.6543],
                "Net_TEX": [-180.9876, -260.3456],
                "Call_IVxOI": [15.789, 12.345],
                "Put_IVxOI": [10.654, 18.987],
                "Call_Vanna_Ratio": [1.2, 0.8],
                "Put_Vanna_Ratio": [0.5, 1.1],
                "Vanna_GEX_Total": [0.4, -0.3],
                "IVxOI": [25.0, 30.0],
                "Median_IVxOI": [27.5, 27.5],
                "Energy_Score": ["High", "Moderate"],
                "Regime": ["Gamma Pin", "Vol Drift Up"],
                "Dealer_Bias": [
                    "Neutral / Mean Reversion",
                    "Dealer Selling → Bearish Fade",
                ],
                "Rel_Dist": [0.02, 0.05],
                "Top5_Regime_Energy_Bias": ["", ""],
                "DateTime": ["2024-05-01T12:00:00Z", "2024-05-01T12:00:00Z"],
                "Call_Vanna_Rank": ["Top 1 : 100.12", ""],
                "Put_Vanna_Rank": ["", "Bottom 1 : 90.99"],
                "Net_GEX_Highlight": ["Top 1 : 100.12", ""],
                "DEX_highlight": ["Top 1 : 100.12", ""],
                "Call_TEX_Highlight": ["Top 1 : 100.12", ""],
                "Put_TEX_Highlight": ["", "Top 1 : 90.99"],
                "TEX_highlight": ["", "Top 1 : 90.99"],
                "Call_IVxOI_Rank": ["Top 1 : 100.12", ""],
                "Put_IVxOI_Rank": ["", "Top 1 : 90.99"],
            },
            index=index,
        )
    else:
        summary_df = summary_df.copy()
        index = summary_df.index

    return ProcessingResult(
        ticker="TEST",
        expiry="2024-05-17",
        total_gex=summary_df["Net_GEX"].sum(),
        total_vanna=summary_df["Net_Vanna"].sum(),
        call_gex=summary_df["Call_GEX"].sum(),
        put_gex=summary_df["Put_GEX"].sum(),
        call_vanna=summary_df["Call_Vanna"].sum(),
        put_vanna=summary_df["Put_Vanna"].sum(),
        gex_by_strike={float(strike): float(summary_df.at[strike, "Net_GEX"]) for strike in index},
        vanna_by_strike={float(strike): float(summary_df.at[strike, "Net_Vanna"]) for strike in index},
        source_path=Path("dummy.csv"),
        output_directory=tmp_path,
        strike_type_metrics=[],
        call_vanna_ratio_by_strike={float(strike): float(summary_df.at[strike, "Call_Vanna_Ratio"]) for strike in index},
        put_vanna_ratio_by_strike={float(strike): float(summary_df.at[strike, "Put_Vanna_Ratio"]) for strike in index},
        vanna_gex_total_by_strike={float(strike): float(summary_df.at[strike, "Vanna_GEX_Total"]) for strike in index},
        energy_score_by_strike={float(strike): summary_df.at[strike, "Energy_Score"] for strike in index},
        regime_by_strike={float(strike): summary_df.at[strike, "Regime"] for strike in index},
        dealer_bias_by_strike={float(strike): summary_df.at[strike, "Dealer_Bias"] for strike in index},
        ivxoi_by_strike={float(strike): float(summary_df.at[strike, "IVxOI"]) for strike in index},
        rel_dist_by_strike={float(strike): float(summary_df.at[strike, "Rel_Dist"]) for strike in index},
        top5_bias_summary={float(strike): summary_df.at[strike, "Top5_Regime_Energy_Bias"] for strike in index},
        median_ivxoi=float(summary_df["Median_IVxOI"].iloc[0]),
        iv_direction="down",
        strike_summary_df=summary_df,
        top5_detail={},
        spot_price_used=100.0,
    )


def test_highlight_log_records_highlighted_values(tmp_path):
    analyzer = BarchartOptionsAnalyzer(create_charts=False)
    result = _build_processing_result(tmp_path)

    analyzer._write_outputs(result)

    highlight_path = tmp_path / "highlight_logs" / "TEST_highlight_log.csv"
    assert highlight_path.exists()

    log_df = pd.read_csv(highlight_path, thousands=",", na_values=[""], keep_default_na=True)
    expected_columns = [
        "Ticker",
        "Expiry",
        "Run_Timestamp",
        "Strike",
        "Net_DEX",
        "Call_Vanna",
        "Put_Vanna",
        "Net_GEX",
        "Call_TEX",
        "Put_TEX",
        "Net_TEX",
        "Call_IVxOI",
        "Put_IVxOI",
    ]
    assert list(log_df.columns) == expected_columns

    # All highlighted strikes should be logged and sorted by ticker then strike
    assert log_df.shape[0] == 2
    assert log_df.loc[0, "Strike"] == pytest.approx(90.99)
    assert log_df.loc[1, "Strike"] == pytest.approx(100.12)

    # All values from the summary row should be preserved in the log
    first_row = log_df.iloc[0]
    assert first_row["Net_DEX"] == pytest.approx(950.12, rel=1e-3)
    assert first_row["Call_Vanna"] == pytest.approx(40.79, rel=1e-3)
    assert first_row["Put_Vanna"] == pytest.approx(-90.99, rel=1e-3)
    assert first_row["Net_GEX"] == pytest.approx(-200.43, rel=1e-3)
    assert first_row["Call_TEX"] == pytest.approx(-80.99, rel=1e-3)
    assert first_row["Put_TEX"] == pytest.approx(-180.65, rel=1e-3)
    assert first_row["Net_TEX"] == pytest.approx(-260.35, rel=1e-3)
    assert first_row["Call_IVxOI"] == pytest.approx(12.35, rel=1e-3)
    assert first_row["Put_IVxOI"] == pytest.approx(18.99, rel=1e-3)

    second_row = log_df.iloc[1]
    assert second_row["Net_DEX"] == pytest.approx(1000.57, rel=1e-3)
    assert second_row["Call_Vanna"] == pytest.approx(80.35, rel=1e-3)
    assert second_row["Put_Vanna"] == pytest.approx(-30.43, rel=1e-3)
    assert second_row["Net_GEX"] == pytest.approx(150.68, rel=1e-3)
    assert second_row["Call_TEX"] == pytest.approx(-120.68, rel=1e-3)
    assert second_row["Put_TEX"] == pytest.approx(-60.54, rel=1e-3)
    assert second_row["Net_TEX"] == pytest.approx(-180.99, rel=1e-3)
    assert second_row["Call_IVxOI"] == pytest.approx(15.79, rel=1e-3)
    assert second_row["Put_IVxOI"] == pytest.approx(10.65, rel=1e-3)

    # Confirm numbers are written with thousands separators in the CSV output
    csv_contents = highlight_path.read_text(encoding="utf-8")
    assert '"1,000.57"' in csv_contents


def test_highlight_log_appends_full_rows_for_successive_runs(tmp_path):
    analyzer = BarchartOptionsAnalyzer(create_charts=False)
    initial_result = _build_processing_result(tmp_path)
    analyzer._write_outputs(initial_result)

    summary_df = initial_result.strike_summary_df.copy()
    highlight_columns = [
        "Call_Vanna_Rank",
        "Put_Vanna_Rank",
        "Net_GEX_Highlight",
        "DEX_highlight",
        "Call_TEX_Highlight",
        "Put_TEX_Highlight",
        "TEX_highlight",
        "Call_IVxOI_Rank",
        "Put_IVxOI_Rank",
    ]
    for column in highlight_columns:
        summary_df[column] = ""

    summary_df.loc[:, "DateTime"] = [
        "2024-05-02T12:00:00Z",
        "2024-05-02T12:00:00Z",
    ]

    summary_df.loc[100.1234, "Net_DEX"] = 1200.12
    summary_df.loc[90.9876, "Net_DEX"] = 940.45
    summary_df.loc[100.1234, "Call_Vanna"] = 75.55
    summary_df.loc[90.9876, "Call_Vanna"] = 52.66
    summary_df.loc[100.1234, "Put_Vanna"] = -28.44
    summary_df.loc[90.9876, "Put_Vanna"] = -85.77
    summary_df.loc[100.1234, "Net_GEX"] = 165.43
    summary_df.loc[90.9876, "Net_GEX"] = -215.88
    summary_df.loc[100.1234, "Call_TEX"] = -130.22
    summary_df.loc[90.9876, "Call_TEX"] = -95.11
    summary_df.loc[100.1234, "Put_TEX"] = -70.33
    summary_df.loc[90.9876, "Put_TEX"] = -165.22
    summary_df.loc[100.1234, "Net_TEX"] = -200.55
    summary_df.loc[90.9876, "Net_TEX"] = -260.33
    summary_df.loc[100.1234, "Call_IVxOI"] = 16.23
    summary_df.loc[90.9876, "Call_IVxOI"] = 13.67
    summary_df.loc[100.1234, "Put_IVxOI"] = 11.45
    summary_df.loc[90.9876, "Put_IVxOI"] = 19.21

    summary_df.loc[100.1234, "Call_Vanna_Rank"] = "Top 1 : 100.12"
    summary_df.loc[100.1234, "Net_GEX_Highlight"] = "Top 1 : 100.12"
    summary_df.loc[100.1234, "DEX_highlight"] = "Top 1 : 100.12"
    summary_df.loc[90.9876, "Put_Vanna_Rank"] = "Bottom 1 : 90.99"
    summary_df.loc[90.9876, "Put_TEX_Highlight"] = "Top 1 : 90.99"
    summary_df.loc[90.9876, "TEX_highlight"] = "Top 1 : 90.99"
    summary_df.loc[90.9876, "Put_IVxOI_Rank"] = "Top 1 : 90.99"

    follow_up_result = _build_processing_result(tmp_path, summary_df=summary_df)
    analyzer._write_outputs(follow_up_result)

    highlight_path = tmp_path / "highlight_logs" / "TEST_highlight_log.csv"
    log_df = pd.read_csv(highlight_path, thousands=",", na_values=[""], keep_default_na=True)

    assert log_df.shape[0] == 4

    first_strike_rows = log_df.loc[np.isclose(log_df["Strike"], 90.99, rtol=1e-3)].reset_index(drop=True)
    assert list(first_strike_rows["Run_Timestamp"]) == [
        "2024-05-02T12:00:00Z",
        "2024-05-01T12:00:00Z",
    ]
    latest_first_strike = first_strike_rows.iloc[0]
    assert latest_first_strike["Net_DEX"] == pytest.approx(940.45)
    assert latest_first_strike["Call_Vanna"] == pytest.approx(52.66)
    assert latest_first_strike["Put_Vanna"] == pytest.approx(-85.77)
    assert latest_first_strike["Net_GEX"] == pytest.approx(-215.88)
    assert latest_first_strike["Call_TEX"] == pytest.approx(-95.11)
    assert latest_first_strike["Put_TEX"] == pytest.approx(-165.22)
    assert latest_first_strike["Net_TEX"] == pytest.approx(-260.33)
    assert latest_first_strike["Call_IVxOI"] == pytest.approx(13.67)
    assert latest_first_strike["Put_IVxOI"] == pytest.approx(19.21)

    previous_first_strike = first_strike_rows.iloc[1]
    assert previous_first_strike["Net_DEX"] == pytest.approx(950.12, rel=1e-3)
    assert previous_first_strike["Call_Vanna"] == pytest.approx(40.79, rel=1e-3)
    assert previous_first_strike["Put_Vanna"] == pytest.approx(-90.99, rel=1e-3)
    assert previous_first_strike["Net_GEX"] == pytest.approx(-200.43, rel=1e-3)
    assert previous_first_strike["Call_TEX"] == pytest.approx(-80.99, rel=1e-3)
    assert previous_first_strike["Put_TEX"] == pytest.approx(-180.65, rel=1e-3)
    assert previous_first_strike["Net_TEX"] == pytest.approx(-260.35, rel=1e-3)
    assert previous_first_strike["Call_IVxOI"] == pytest.approx(12.35, rel=1e-3)
    assert previous_first_strike["Put_IVxOI"] == pytest.approx(18.99, rel=1e-3)

    second_strike_rows = log_df.loc[np.isclose(log_df["Strike"], 100.12, rtol=1e-3)].reset_index(drop=True)
    assert list(second_strike_rows["Run_Timestamp"]) == [
        "2024-05-02T12:00:00Z",
        "2024-05-01T12:00:00Z",
    ]
    latest_second_strike = second_strike_rows.iloc[0]
    assert latest_second_strike["Net_DEX"] == pytest.approx(1200.12)
    assert latest_second_strike["Call_Vanna"] == pytest.approx(75.55)
    assert latest_second_strike["Put_Vanna"] == pytest.approx(-28.44)
    assert latest_second_strike["Net_GEX"] == pytest.approx(165.43)
    assert latest_second_strike["Call_TEX"] == pytest.approx(-130.22)
    assert latest_second_strike["Put_TEX"] == pytest.approx(-70.33)
    assert latest_second_strike["Net_TEX"] == pytest.approx(-200.55)
    assert latest_second_strike["Call_IVxOI"] == pytest.approx(16.23)
    assert latest_second_strike["Put_IVxOI"] == pytest.approx(11.45)

    previous_second_strike = second_strike_rows.iloc[1]
    assert previous_second_strike["Net_DEX"] == pytest.approx(1000.57, rel=1e-3)
    assert previous_second_strike["Call_Vanna"] == pytest.approx(80.35, rel=1e-3)
    assert previous_second_strike["Put_Vanna"] == pytest.approx(-30.43, rel=1e-3)
    assert previous_second_strike["Net_GEX"] == pytest.approx(150.68, rel=1e-3)
    assert previous_second_strike["Call_TEX"] == pytest.approx(-120.68, rel=1e-3)
    assert previous_second_strike["Put_TEX"] == pytest.approx(-60.54, rel=1e-3)
    assert previous_second_strike["Net_TEX"] == pytest.approx(-180.99, rel=1e-3)
    assert previous_second_strike["Call_IVxOI"] == pytest.approx(15.79, rel=1e-3)
    assert previous_second_strike["Put_IVxOI"] == pytest.approx(10.65, rel=1e-3)

