"""Tests for the highlight log output generated by the analyzer."""

from __future__ import annotations

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd

from barchart.analyzer import BarchartOptionsAnalyzer, ProcessingResult


def _build_processing_result(tmp_path: Path) -> ProcessingResult:
    index = pd.Index([100.0, 90.0])
    summary_df = pd.DataFrame(
        {
            "Net_GEX": [150.0, -200.0],
            "Net_Vanna": [50.0, -60.0],
            "Call_Vanna": [80.0, 40.0],
            "Put_Vanna": [-30.0, -90.0],
            "Call_GEX": [90.0, 60.0],
            "Put_GEX": [60.0, -260.0],
            "Call_DEX": [600.0, 500.0],
            "Put_DEX": [400.0, 450.0],
            "Net_DEX": [1000.0, 950.0],
            "Call_TEX": [-120.0, -80.0],
            "Put_TEX": [-60.0, -180.0],
            "Net_TEX": [-180.0, -260.0],
            "Call_IVxOI": [15.0, 12.0],
            "Put_IVxOI": [10.0, 18.0],
            "Call_Vanna_Ratio": [1.2, 0.8],
            "Put_Vanna_Ratio": [0.5, 1.1],
            "Vanna_GEX_Total": [0.4, -0.3],
            "IVxOI": [25.0, 30.0],
            "Median_IVxOI": [27.5, 27.5],
            "Energy_Score": ["High", "Moderate"],
            "Regime": ["Gamma Pin", "Vol Drift Up"],
            "Dealer_Bias": [
                "Neutral / Mean Reversion",
                "Dealer Selling → Bearish Fade",
            ],
            "Rel_Dist": [0.02, 0.05],
            "Top5_Regime_Energy_Bias": ["", ""],
            "DateTime": ["2024-05-01T12:00:00Z", "2024-05-01T12:00:00Z"],
            "Call_Vanna_Highlight": ["Top 1 : 100", ""],
            "Put_Vanna_Highlight": ["", "Bottom 1 : 90"],
            "Net_GEX_Highlight": ["Top 1 : 100", ""],
            "DEX_highlight": ["Top 1 : 100", ""],
            "Call_TEX_Highlight": ["Top 1 : 100", ""],
            "Put_TEX_Highlight": ["", "Top 1 : 90"],
            "TEX_highlight": ["", "Top 1 : 90"],
            "Call_IVxOI_Highlight": ["Top 1 : 100", ""],
            "Put_IVxOI_Highlight": ["", "Top 1 : 90"],
        },
        index=index,
    )

    return ProcessingResult(
        ticker="TEST",
        expiry="2024-05-17",
        total_gex=summary_df["Net_GEX"].sum(),
        total_vanna=summary_df["Net_Vanna"].sum(),
        call_gex=summary_df["Call_GEX"].sum(),
        put_gex=summary_df["Put_GEX"].sum(),
        call_vanna=summary_df["Call_Vanna"].sum(),
        put_vanna=summary_df["Put_Vanna"].sum(),
        gex_by_strike={float(strike): float(summary_df.at[strike, "Net_GEX"]) for strike in index},
        vanna_by_strike={float(strike): float(summary_df.at[strike, "Net_Vanna"]) for strike in index},
        source_path=Path("dummy.csv"),
        output_directory=tmp_path,
        strike_type_metrics=[],
        call_vanna_ratio_by_strike={float(strike): float(summary_df.at[strike, "Call_Vanna_Ratio"]) for strike in index},
        put_vanna_ratio_by_strike={float(strike): float(summary_df.at[strike, "Put_Vanna_Ratio"]) for strike in index},
        vanna_gex_total_by_strike={float(strike): float(summary_df.at[strike, "Vanna_GEX_Total"]) for strike in index},
        energy_score_by_strike={float(strike): summary_df.at[strike, "Energy_Score"] for strike in index},
        regime_by_strike={float(strike): summary_df.at[strike, "Regime"] for strike in index},
        dealer_bias_by_strike={float(strike): summary_df.at[strike, "Dealer_Bias"] for strike in index},
        ivxoi_by_strike={float(strike): float(summary_df.at[strike, "IVxOI"]) for strike in index},
        rel_dist_by_strike={float(strike): float(summary_df.at[strike, "Rel_Dist"]) for strike in index},
        top5_bias_summary={float(strike): summary_df.at[strike, "Top5_Regime_Energy_Bias"] for strike in index},
        median_ivxoi=float(summary_df["Median_IVxOI"].iloc[0]),
        iv_direction="down",
        strike_summary_df=summary_df,
    )


def test_highlight_log_records_highlighted_values(tmp_path):
    analyzer = BarchartOptionsAnalyzer(create_charts=False)
    result = _build_processing_result(tmp_path)

    analyzer._write_outputs(result)

    highlight_path = tmp_path / "TEST_2024-05-17_highlight_log.csv"
    assert highlight_path.exists()

    log_df = pd.read_csv(highlight_path)
    expected_columns = [
        "Ticker",
        "Expiry",
        "Run_Timestamp",
        "Strike",
        "Net_DEX",
        "Call_Vanna",
        "Put_Vanna",
        "Net_GEX",
        "Call_TEX",
        "Put_TEX",
        "Net_TEX",
        "Call_IVxOI",
        "Put_IVxOI",
    ]
    assert list(log_df.columns) == expected_columns

    # All highlighted strikes should be logged and sorted descending within the run
    assert log_df.shape[0] == 2
    assert log_df.loc[0, "Strike"] == 100.0
    assert log_df.loc[1, "Strike"] == 90.0

    # Only values with highlights should be populated
    first_row = log_df.iloc[0]
    assert first_row["Net_DEX"] == 1000.0
    assert first_row["Call_Vanna"] == 80.0
    assert pd.isna(first_row["Put_Vanna"])
    assert first_row["Call_TEX"] == -120.0
    assert pd.isna(first_row["Put_TEX"])

    second_row = log_df.iloc[1]
    assert pd.isna(second_row["Call_Vanna"])
    assert second_row["Put_Vanna"] == -90.0
    assert pd.isna(second_row["Net_GEX"])
    assert second_row["Put_TEX"] == -180.0
    assert second_row["Net_TEX"] == -260.0
    assert second_row["Put_IVxOI"] == 18.0

